# Generated by Django 4.0.6 on 2022-08-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='media/videos/%Y/%m/%d/'),
        ),
    ]
