# Generated by Django 4.0.6 on 2022-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_videos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(default=4, unique=True),
            preserve_default=False,
        ),
    ]
