# Generated by Django 4.0.6 on 2022-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_categories_videos_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.AddField(
            model_name='videos',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='media/videos/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d/'),
        ),
    ]
