# Generated by Django 4.0.6 on 2022-08-30 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0011_rename_user_videos_uploaded_by_videos_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
